### ISSUE TITLE
Feedlinks 404

### ISSUE THREAD

**Issue by haeckle** [maxammann/blog#1]
Hi, the links in your feed still point to the github.io-site. I think you should update the baseurl here:
https://github.com/maxammann/blog/blob/b0d6c14f2dc6f50f68b8e74871af05d6337a12a3/config.toml#L1
But otherwise thanks sharing your thoughts!

**Comment by maxammann** [comment]
Thank you very much for reporting :) Updated the url.

Do I actually have a reader here? :P Mostly doing it for documentation purposes.

**Comment by haeckle** [comment]
Apparently ;) 
some posts catched my interest... (i.e. Pulseaudio or Pi related stuff)
